source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'xxcolor' do
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'UMengAnalytics-NO-IDFA'
  pod 'SnapKit', '~> 3.2.0'
  pod 'Toast-Swift', '~> 2.0.0'
  pod 'Alamofire', '~> 4.4'
  pod 'HandyJSON', '~> 1.6.1'
  pod "ESTabBarController-swift"
end
